# Generated by Django 6.0.3 on 2026-04-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.FloatField()),
                ('damage_detected', models.BooleanField()),
                ('risk_level', models.CharField(max_length=50)),
            ],
        ),
    ]
