# Generated by Django 6.0.3 on 2026-04-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analysis',
            table='Analysis',
        ),
    ]
