# Generated by Django 6.0.3 on 2026-04-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_analysis_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='damage_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='health_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
