# Generated by Django 6.0.3 on 2026-04-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('trees_planted', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
