# Generated by Django 6.0.3 on 2026-04-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoration', '0004_restorationproject_restorationevent_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restorationevent',
            table='Restoration Event',
        ),
    ]
