# Generated by Django 6.0.3 on 2026-04-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('community', 'Community'), ('organization', 'Organization')], max_length=20),
        ),
    ]
